// What every conformance measurement shares: a browser, a page, and a font proven
// to be the one asked for. Nothing compares pixels -- Chrome's rasteriser is not
// ours -- so what crosses is geometry, colour at derived points, ink spans against
// a threshold and laid-out lines. Read the agreeing rows first.

import { readFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { chromium, firefox, webkit } from 'playwright'

const HERE = dirname(fileURLToPath(import.meta.url))

/** The repository's own face, which every text measurement uses. */
export const FONT = {
  family: 'Fixture',
  path: resolve(HERE, '../../../../crates/meo-canvas-core/tests/assets/fonts/Oswald-VariableFont_wght.ttf'),
}

/**
 * The engines {@link open} launches, by the name a caller passes. Gecko shares no
 * ancestor with Blink and WebKit, so a row all three give reads CSS; a split is
 * settled from the specification, as `WEBKIT_ALONE` records for `ratio-stretch-main.tsv`.
 */
const ENGINES = { chromium, firefox, webkit }

/**
 * What each {@link open} of this run launched, keyed by engine in insertion order,
 * for {@link table} to stamp -- one place every tool's table passes through, so a
 * table measured on three engines names the build of each.
 */
const launched = new Map()

/**
 * Opens a page with the font embedded and proved to have loaded:
 * `document.fonts.load` resolves either way, so a fallback face would measure
 * silently. This throws instead, naming the family.
 */
export async function open(engine = 'chromium') {
  const launch = ENGINES[engine]
  if (launch === undefined) {
    throw new Error(`no engine named "${engine}"; the harness launches ${Object.keys(ENGINES).join(', ')}`)
  }
  const font = await readFile(FONT.path)
  const browser = await launch.launch()
  launched.set(engine, browser.version())
  const page = await browser.newPage()

  await page.setContent(`<!doctype html>
<meta charset="utf-8">
<style>
  @font-face {
    font-family: '${FONT.family}';
    src: url(data:font/ttf;base64,${font.toString('base64')}) format('truetype');
  }
  html, body { margin: 0; padding: 0; }
</style>
<body></body>`)

  await page.evaluate(async family => {
    // 100px so the load is unambiguous, then the check, which is the assertion
    // this page exists for.
    await document.fonts.load(`100px "${family}"`)
    if (!document.fonts.check(`100px "${family}"`)) {
      throw new Error(`the face "${family}" did not load; every measurement from this page would be the fallback's`)
    }
  }, FONT.family)

  return {
    page,
    /** Closes the browser. Always, even where a measurement threw. */
    async close() {
      await browser.close()
    },
  }
}

/**
 * Waits for every asset on the page to be usable, and throws if one is not: an
 * undecoded image measures as an empty box. Fonts and images are the only asset
 * kinds, since the CSS is inline and the font a data URL; a third must be added here.
 */
export async function settle(page) {
  await page.evaluate(async () => {
    await document.fonts.ready
    const images = [...document.images]
    await Promise.all(
      images.map(async image => {
        try {
          await image.decode()
        } catch (cause) {
          throw new Error(`an image on this page never decoded: ${image.src.slice(0, 60)}`, { cause })
        }
      }),
    )
    const broken = images.filter(image => image.naturalWidth === 0)
    if (broken.length > 0) {
      throw new Error(`${broken.length} image(s) decoded to nothing; every measurement from this page would be of an empty box`)
    }
  })
}

/** What each engine is called in prose, for the stamp. */
const ENGINE_NAMES = { chromium: 'Chrome Headless Shell', firefox: 'Firefox', webkit: 'WebKit' }

/**
 * Writes a table beside the ones the walkers already read: a `.tsv` with a
 * commented header, since these are read by eye as often as by a test.
 */
export function table(lines) {
  // The stamp is written here, at the moment of measurement, so regenerating a
  // table restamps it with the browser that produced its rows.
  if (launched.size === 0) {
    throw new Error('table() before open(): the browser version is not known, and an unstamped table cannot say which Chrome produced it')
  }
  const [first, ...rest] = lines
  // **The single-engine line is unchanged, deliberately.** Twenty-two tables
  // carry it and are regenerated by `just conformance`; a reworded stamp would
  // rewrite all of them in a commit about one table, and a diff that size is
  // one nobody reads.
  const stamp =
    launched.size === 1 && launched.has('chromium')
      ? [`# Measured on Chrome Headless Shell ${launched.get('chromium')}, the chromium Playwright pins here.`]
      : [...launched].map(([engine, version]) => `# Measured on ${ENGINE_NAMES[engine]} ${version}, the ${engine} Playwright pins here.`)
  return `${[first, ...stamp, ...rest].join('\n')}\n`
}
