/**
 * Finding the compiled addon: the override, this working tree, or the platform
 * package installed for this target. Every key in {@link PLATFORM_PACKAGES} is a
 * target CI builds, generated with `optionalDependencies` from `TARGETS` in
 * `tools/stage-platform-package.mjs`.
 */

import { createRequire } from 'node:module'

/**
 * The platform packages, keyed by the triple {@link target} derives, generated by
 * `tools/generate-platform-packages.mjs` and re-exported so this module stays the
 * one place a caller asks about platforms.
 */
import { PLATFORM_PACKAGES } from './generated/platform-packages.js'

export { PLATFORM_PACKAGES }

/** The environment variable that overrides every other path. */
const OVERRIDE = 'MEO_CANVAS_ADDON'

/**
 * The addon built in this working tree, beside the package's own files.
 *
 * `just addon` writes it here, and it wins over an installed platform package
 * so that a checkout tests what it just built rather than what npm resolved.
 */
const IN_TREE = '../meo-canvas.node'

/**
 * Where the repository is: most readers of a loader failure ran `npm install` and
 * have no checkout, so `just addon` alone would read as a broken package.
 */
const BUILD_IT = 'Build one from a checkout of https://github.com/l7aromeo/meo-canvas with `just addon`.'

/**
 * Which C library this Node runs against, and its version: `glibcVersionRuntime` is
 * in the process report only on glibc, and this is `undefined` off Linux. The
 * version is kept because it decides whether a binary built on a newer glibc loads.
 */
function libc(): { readonly family: 'glibc' | 'musl'; readonly version?: string } | undefined {
  if (process.platform !== 'linux') return undefined
  const header = process.report?.getReport() as { header?: { glibcVersionRuntime?: string } } | undefined
  const version = header?.header?.glibcVersionRuntime
  return version === undefined ? { family: 'musl' } : { family: 'glibc', version }
}

/**
 * The triple used to look a package up and to name the host in an error:
 * `platform-arch`, plus the C library on Linux, where a glibc and a musl binary are
 * different artefacts for the same `linux-x64`.
 */
export function target(): string {
  const host = `${process.platform}-${process.arch}`
  const family = libc()?.family
  if (family === undefined) return host
  // `glibc` is the C library and `gnu` the target suffix: npm's `libc` field says
  // `glibc`, and every triple naming it, `@meo-canvas/linux-x64-gnu` included, says
  // `gnu`.
  return `${host}-${family === 'glibc' ? 'gnu' : family}`
}

/**
 * The floors a platform package declares, or `undefined` where it declares none.
 * Read from its own `package.json`, which stays readable when the binary beside it
 * will not load — the moment the numbers are needed.
 */
function declaredFloors(platformPackage: string): { glibc?: string; glibcxx?: string } | undefined {
  const require = createRequire(import.meta.url)
  try {
    const manifest = require(`${platformPackage}/package.json`) as {
      meoCanvas?: { floors?: { glibc?: string; glibcxx?: string } }
    }
    return manifest.meoCanvas?.floors
  } catch {
    // An older platform package predating the declaration, or one whose
    // manifest is unreadable. Neither is worth failing over: the diagnosis is
    // an improvement on the loader's message, not a precondition for it.
    return undefined
  }
}

/** Whether `version` is older than `floor`, both dotted numbers like `2.35`. */
function older(version: string, floor: string): boolean {
  const parts = (value: string) => value.split('.').map(part => Number.parseInt(part, 10))
  const [left, right] = [parts(version), parts(floor)]
  for (let index = 0; index < Math.max(left.length, right.length); index += 1) {
    const [a, b] = [left[index] ?? 0, right[index] ?? 0]
    // A non-numeric component makes the comparison meaningless rather than
    // false. Saying nothing beats asserting an ordering that was never read.
    if (Number.isNaN(a) || Number.isNaN(b)) return false
    if (a !== b) return a < b
  }
  return false
}

/**
 * Why an installed platform package would not load, with the host's number, what
 * the binary wants, and the fix. It diagnoses a failure and predicts none: an
 * unversioned symbol such as `_M_replace_cold` can fail a binary that meets every
 * declared floor, and only loading it can tell.
 */
function loadFailure(platformPackage: string, cause: unknown): string {
  const detail = cause instanceof Error ? cause.message : String(cause)
  const fix = `${BUILD_IT} Or point ${OVERRIDE} at a binary you built.`

  // A shared object the binary needs and the host lacks. No published artefact
  // reaches this, since fontconfig and freetype are linked statically, but a
  // dynamically linked target, a binary named by `MEO_CANVAS_ADDON` or musl's
  // `libstdc++` can; it was reached by adding a `DT_NEEDED` nothing provides.
  const missing = missingLibrary(detail)
  if (missing !== undefined) {
    return `${platformPackage} is installed, and loading it needs ${missing}, which this host does not have. ${installing(missing)} ${fix}`
  }

  // A glibc older than the binary was built against, named against the floor
  // the package declares so the message carries both numbers rather than one.
  const host = libc()
  const floors = declaredFloors(platformPackage)
  if (host?.family === 'glibc' && host.version !== undefined && floors?.glibc !== undefined && older(host.version, floors.glibc)) {
    return (
      `${platformPackage} is installed, and it needs glibc ${floors.glibc} or newer; this host has ${host.version}. ` +
      `No package installs around that -- it is the C library the system is built on. ` +
      // `fix` is appended whole, as sentences of its own.
      `Run on a newer image. ${fix}`
    )
  }

  // Everything else, including the unversioned-symbol case the floors cannot
  // see. The loader's text is passed through rather than paraphrased: it names
  // the symbol, and a guess about the cause would be worse than the fact.
  return `${platformPackage} is installed and its binary would not load: ${detail}. ${fix}`
}

/**
 * The shared object a loader could not find, in either loader's wording: glibc's
 * `libX: cannot open shared object file` or musl's `Error loading shared library
 * libX: No such file or directory`. The musl match requires `No such file`, since
 * that prefix also carries `Exec format error`, a binary for the wrong architecture.
 */
function missingLibrary(detail: string): string | undefined {
  const glibc = /([\w.+-]+\.so[\w.]*): cannot open shared object file/.exec(detail)
  if (glibc !== null) return glibc[1]
  const musl = /Error loading shared library ([\w.+-]+\.so[\w.]*): No such file or directory/.exec(detail)
  return musl?.[1]
}

/**
 * How to install the shared object that is missing, named for the one found.
 * Packages are named only where known; otherwise the command that asks the
 * distribution is more use than a guess typed as a fact.
 */
function installing(library: string): string {
  if (/^libfontconfig|^libfreetype/.test(library)) {
    return 'Install it -- `libfontconfig1` and `libfreetype6` on Debian and Ubuntu, `fontconfig` and `freetype` on RHEL-family images.'
  }
  if (/^libstdc\+\+/.test(library)) {
    return 'Install it -- `libstdc++6` on Debian and Ubuntu, `libstdc++` on Alpine and on RHEL-family images. Any image that can run Node already has it, since Node links it too.'
  }
  return 'Install whatever your distribution provides it in -- `apt-file search`, `dnf provides` or `apk info --who-owns` will name the package.'
}

/** Every attempt made, so a failure can say what was tried rather than what was last tried. */
interface Attempt {
  readonly where: string
  readonly cause: unknown
}

/**
 * The addon, from the override, the working tree or the platform package, the most
 * specific intent first. Each failure is kept, so an error names every place tried
 * rather than the last.
 */
export function resolveAddon<T>(): T {
  const require = createRequire(import.meta.url)
  const attempts: Attempt[] = []

  const override = process.env[OVERRIDE]
  if (override !== undefined && override !== '') {
    try {
      return require(override) as T
    } catch (cause) {
      // An override that does not load is an error rather than a fallback: it
      // was set deliberately, and silently loading a different binary than the
      // one named is how a test reports on code nobody asked it about.
      throw new Error(`${OVERRIDE} is set to ${override}, and no addon loaded from there`, { cause })
    }
  }

  try {
    return require(IN_TREE) as T
  } catch (cause) {
    attempts.push({ where: `this working tree (${IN_TREE}, written by \`just addon\`)`, cause })
  }

  const host = target()
  const platformPackage = PLATFORM_PACKAGES[host]
  if (platformPackage === undefined) {
    throw new Error(
      // `host` already carries the libc on Linux, so a musl host reads as
      // `linux-x64-musl`.
      `no prebuilt addon is published for ${host}. ` +
        `The published targets are ${Object.keys(PLATFORM_PACKAGES).join(', ')}. ` +
        `${BUILD_IT} Or point ${OVERRIDE} at a binary you built.`,
    )
  }

  // Resolved-but-unloadable and not installed have different fixes, so they are
  // told apart with `require.resolve` rather than by matching the loader's wording.
  let resolved: string | undefined
  try {
    resolved = require.resolve(platformPackage)
  } catch {
    attempts.push({ where: `the platform package ${platformPackage}`, cause: undefined })
  }

  if (resolved !== undefined) {
    try {
      return require(platformPackage) as T
    } catch (cause) {
      // The package is installed and its binary would not load. Everything
      // below is about saying why, because the loader's own message names a
      // symbol and nothing a reader can act on.
      throw new Error(loadFailure(platformPackage, cause), { cause })
    }
  }

  // One message for three causes it cannot tell apart: skipped at install, bundled
  // away from its `node_modules`, or never installed. The bundler case is named
  // because the addon is resolved at run time, so a bundle works beside the tree it
  // was built in and fails once copied into an image alone.
  throw new Error(
    `the addon for ${host} was not found in ${attempts.length} places: ` +
      attempts.map(attempt => attempt.where).join('; ') +
      `. Install the package with its optional dependencies -- \`--omit=optional\` and a lockfile written without them both skip it. ` +
      `If this code was bundled, mark meo-canvas external instead, since the addon is resolved at run time and no bundler can follow it. ` +
      BUILD_IT,
    { cause: attempts[attempts.length - 1]?.cause },
  )
}
