/**
 * Easing curves, written against a table of v1's own answers.
 *
 * # Why this was not written from the Rust
 *
 * The Rust half of this port exists and this file was written without reading
 * it. **If either surface is written from the other, a misreading of v1 reaches
 * both and the agreement test passes while both are wrong.** The referee is
 * `crates/meo-canvas-core/tests/assets/animate/*.tsv`, generated by running
 * v1's built module at tag `v9.0.2` before either implementation existed.
 *
 * # Exact, with no tolerance
 *
 * The tables are printed at JavaScript's default precision — the shortest
 * string that round-trips an `f64` — so both surfaces parse the identical
 * number and a comparison is not silently an epsilon. This side runs on the
 * same engine that produced them, so **it should agree to the bit and the test
 * asserts exactly that.**
 *
 * # The input is clamped and the output is not
 *
 * The grid runs to `-0.25` and `1.25`, so clamping is data rather than a
 * decision taken here — and the data says something more particular than "it
 * clamps". At `t = -0.25` the table holds `0` for some curves and
 * `1.1102230246251565e-16` for others. **A curve that clamped its output would
 * give zero for all of them.** What v1 does is clamp `t` and then evaluate, and
 * the residue is the curve's own arithmetic at exactly `0`. So:
 *
 * - clamp the input, never the output
 * - do not special-case `t <= 0` to `0`, which would lose the residue
 *
 * Overshoot is untouched by this: `back` and `elastic` exceed `0..1` in their
 * **output** inside the clamped input range, and are meant to. The clamp that
 * matters for colour happens where a colour becomes paint, not here.
 *
 * # Arithmetic written in v1's shape
 *
 * `(a * t + b) * t + c` and `a * t * t + b * t + c` are the same algebra and
 * not the same float. The expressions here are grouped as v1 groups them, and
 * a build step that reassociated them would be a defect rather than an
 * optimisation.
 */

/** Every curve in the catalogue, by the name v1 gives it. */
export type EasingName =
  | 'linear'
  | 'inSine'
  | 'outSine'
  | 'inOutSine'
  | 'inQuad'
  | 'outQuad'
  | 'inOutQuad'
  | 'inCubic'
  | 'outCubic'
  | 'inOutCubic'
  | 'inQuart'
  | 'outQuart'
  | 'inOutQuart'
  | 'inQuint'
  | 'outQuint'
  | 'inOutQuint'
  | 'inExpo'
  | 'outExpo'
  | 'inOutExpo'
  | 'inCirc'
  | 'outCirc'
  | 'inOutCirc'
  | 'inBack'
  | 'outBack'
  | 'inOutBack'
  | 'inElastic'
  | 'outElastic'
  | 'inOutElastic'
  | 'inBounce'
  | 'outBounce'
  | 'inOutBounce'

/** `back`'s overshoot, the constant CSS and every animation library settled on. */
const BACK_OVERSHOOT = 1.70158
/** The elastic oscillation's period, as a fraction of the duration. */
const ELASTIC_PERIOD = 0.3
const BOUNCE_N = 7.5625
const BOUNCE_D = 2.75

/**
 * Turns an ease-in curve into its out and in-out counterparts.
 *
 * **This is the shape v1 uses and copying it is not a stylistic choice.** A
 * closed form for `outQuart` — `1 - (1 - t) ** 4` — is the same algebra as
 * `1 - easeIn(1 - t)` and not the same float: written closed, `outQuart(0.1)`
 * came out `0.3439` where v1 gives `0.3438999999999999`. Every `out` and
 * `inOut` here is a reflection for that reason, and `inOut` in particular is
 * **not** the two-branch form the easing catalogues publish.
 */
const family = (easeIn: (t: number) => number) => ({
  in: (t: number) => easeIn(t),
  out: (t: number) => 1 - easeIn(1 - t),
  inOut: (t: number) => (t < 0.5 ? easeIn(t * 2) / 2 : 1 - easeIn((1 - t) * 2) / 2),
})

const quad = family(t => t * t)
const cubic = family(t => t * t * t)
const quart = family(t => t * t * t * t)
const quint = family(t => t * t * t * t * t)
const sine = family(t => 1 - Math.cos((t * Math.PI) / 2))
// `expo` special-cases `t === 0`, because `2 ** -10` is `0.000977` and not
// zero. A hundredth of a pixel at eight pixels of travel reads as a curve that
// starts almost at rest rather than as a defect, and no fixture would catch it
// — only an exact zero in a table does.
const expo = family(t => (t === 0 ? 0 : Math.pow(2, 10 * t - 10)))
const circ = family(t => 1 - Math.sqrt(1 - t * t))
const back = family(t => (BACK_OVERSHOOT + 1) * t * t * t - BACK_OVERSHOOT * t * t)
// The period is `0.3` of the duration, not the `2 * PI / 3` the easing
// catalogues publish. Those are different curves, not different spellings.
const elastic = family(t => {
  if (t === 0 || t === 1) return t
  return -Math.pow(2, 10 * t - 10) * Math.sin(((t * 10 - 10.75) * (2 * Math.PI)) / ELASTIC_PERIOD)
})

/** Bounce is defined by its out form and mirrored, as everyone writes it. */
const outBounceCurve = (t: number): number => {
  if (t < 1 / BOUNCE_D) return BOUNCE_N * t * t
  if (t < 2 / BOUNCE_D) return BOUNCE_N * (t -= 1.5 / BOUNCE_D) * t + 0.75
  if (t < 2.5 / BOUNCE_D) return BOUNCE_N * (t -= 2.25 / BOUNCE_D) * t + 0.9375
  return BOUNCE_N * (t -= 2.625 / BOUNCE_D) * t + 0.984375
}
const bounce = family(t => 1 - outBounceCurve(1 - t))

const clamp01 = (t: number): number => (t < 0 ? 0 : t > 1 ? 1 : t)

/** The catalogue. Every entry clamps its own input. */
const CURVES: Record<EasingName, (t: number) => number> = {
  linear: t => clamp01(t),
  inSine: t => sine.in(clamp01(t)),
  outSine: t => sine.out(clamp01(t)),
  inOutSine: t => sine.inOut(clamp01(t)),
  inQuad: t => quad.in(clamp01(t)),
  outQuad: t => quad.out(clamp01(t)),
  inOutQuad: t => quad.inOut(clamp01(t)),
  inCubic: t => cubic.in(clamp01(t)),
  outCubic: t => cubic.out(clamp01(t)),
  inOutCubic: t => cubic.inOut(clamp01(t)),
  inQuart: t => quart.in(clamp01(t)),
  outQuart: t => quart.out(clamp01(t)),
  inOutQuart: t => quart.inOut(clamp01(t)),
  inQuint: t => quint.in(clamp01(t)),
  outQuint: t => quint.out(clamp01(t)),
  inOutQuint: t => quint.inOut(clamp01(t)),
  inExpo: t => expo.in(clamp01(t)),
  outExpo: t => expo.out(clamp01(t)),
  inOutExpo: t => expo.inOut(clamp01(t)),
  inCirc: t => circ.in(clamp01(t)),
  outCirc: t => circ.out(clamp01(t)),
  inOutCirc: t => circ.inOut(clamp01(t)),
  inBack: t => back.in(clamp01(t)),
  outBack: t => back.out(clamp01(t)),
  inOutBack: t => back.inOut(clamp01(t)),
  inElastic: t => elastic.in(clamp01(t)),
  outElastic: t => elastic.out(clamp01(t)),
  inOutElastic: t => elastic.inOut(clamp01(t)),
  inBounce: t => bounce.in(clamp01(t)),
  outBounce: t => bounce.out(clamp01(t)),
  inOutBounce: t => bounce.inOut(clamp01(t)),
}

/**
 * One catalogue curve at `t`.
 *
 * Each entry clamps its own input, so a track running past its duration holds
 * at its end value rather than accelerating off the curve. The clamp is on the
 * **input**: `outSine(-0.25)` is the curve's own residue at zero,
 * `1.1102230246251565e-16`, not a flat zero — which is what an output clamp
 * would give and what the table refuses.
 */
export function ease(name: EasingName, t: number): number {
  return CURVES[name](t)
}

/** Every catalogue name, for a caller enumerating them. */
export const EASING_NAMES = Object.keys(CURVES) as EasingName[]

/** Newton's iteration cap before the bisection fallback. */
const BEZIER_MAX_ITERATIONS = 12
/** How close is close enough, for both the solve and the bisection. */
const BEZIER_EPSILON = 1e-6

/**
 * The CSS `cubic-bezier(x1, y1, x2, y2)` curve.
 *
 * **Newton first, bisection as the fallback**, and the fallback is not
 * decoration: Newton stalls where the curve is near-flat, and bisection cannot.
 * The iteration cap and epsilon are v1's, and they are part of the answer
 * rather than of the performance — a different cap converges to a different
 * last bit, so the vectors pin them as surely as they pin the algebra.
 */
export function cubicBezier(x1: number, y1: number, x2: number, y2: number): (t: number) => number {
  const curve = (a: number, b: number, t: number) => {
    const c = 3 * a
    const bTerm = 3 * (b - a) - c
    const aTerm = 1 - c - bTerm
    return ((aTerm * t + bTerm) * t + c) * t
  }
  const slope = (a: number, b: number, t: number) => {
    const c = 3 * a
    const bTerm = 3 * (b - a) - c
    const aTerm = 1 - c - bTerm
    return (3 * aTerm * t + 2 * bTerm) * t + c
  }

  return (time: number): number => {
    const target = clamp01(time)
    if (target === 0 || target === 1) return target

    let t = target
    for (let i = 0; i < BEZIER_MAX_ITERATIONS; i++) {
      const x = curve(x1, x2, t) - target
      if (Math.abs(x) < BEZIER_EPSILON) return curve(y1, y2, t)
      const d = slope(x1, x2, t)
      if (Math.abs(d) < BEZIER_EPSILON) break
      t -= x / d
    }

    let low = 0
    let high = 1
    t = target
    while (high - low > BEZIER_EPSILON) {
      if (curve(x1, x2, t) < target) low = t
      else high = t
      t = (low + high) / 2
    }
    return curve(y1, y2, t)
  }
}

/**
 * Quantises progress into `count` equal jumps, as CSS `steps(count, end)` does.
 *
 * **Floors rather than rounds**, which is what holds each step for its full
 * width: a value a hair below a boundary belongs to the step it is still
 * inside. The vectors sample one part in a billion either side of every
 * boundary for exactly this — floor and round agree everywhere else.
 *
 * The final instant is pinned to `1` so an animation lands on its end value
 * rather than a step short of it.
 */
export function steps(count: number): (t: number) => number {
  if (!Number.isInteger(count) || count < 1) {
    throw new Error(`[canvas] steps() needs at least 1 step (got ${count})`)
  }
  return (t: number) => {
    const clamped = clamp01(t)
    return clamped >= 1 ? 1 : Math.floor(clamped * count) / count
  }
}

/** A spring's physical description. Every field has v1's default. */
export interface SpringConfig {
  readonly from?: number
  readonly to?: number
  readonly stiffness?: number
  readonly damping?: number
  readonly mass?: number
  readonly velocity?: number
}

const DEFAULT_STIFFNESS = 170
const DEFAULT_DAMPING = 26
const DEFAULT_MASS = 1

/**
 * The width of the band around `zeta = 1` treated as critical damping.
 *
 * Not cosmetic: at exactly `zeta = 1` the underdamped branch divides by
 * `omegaD`, which is zero there, and the overdamped branch divides by
 * `fast - slow`, which is also zero. **The band is what keeps a real
 * configuration off both singularities** — and `stiffness: 100, damping: 20`
 * is exactly `zeta = 1`, so it is a configuration a caller reaches by writing
 * round numbers rather than an edge case.
 */
const CRITICAL_BAND = 1e-4

/**
 * A damped harmonic oscillator's position at `t` seconds.
 *
 * Three regimes and each is a different closed form. Displacement is measured
 * **from the target** so it decays to zero and the arithmetic stays symmetric.
 */
export function spring(t: number, config: SpringConfig = {}): number {
  const { from = 0, to = 1, stiffness = DEFAULT_STIFFNESS, damping = DEFAULT_DAMPING, mass = DEFAULT_MASS, velocity = 0 } = config

  if (!(stiffness > 0)) throw new Error(`[canvas] spring stiffness must be greater than 0 (got ${stiffness})`)
  if (!(damping >= 0)) throw new Error(`[canvas] spring damping cannot be negative (got ${damping})`)
  if (!(mass > 0)) throw new Error(`[canvas] spring mass must be greater than 0 (got ${mass})`)

  const omega0 = Math.sqrt(stiffness / mass)
  const zeta = damping / (2 * Math.sqrt(stiffness * mass))

  // Before the motion starts there is nothing to report but where it began.
  if (t <= 0) return from

  const x0 = -(to - from)
  const v0 = velocity
  let displacement: number

  if (Math.abs(zeta - 1) < CRITICAL_BAND) {
    const decay = Math.exp(-omega0 * t)
    displacement = (x0 + (v0 + omega0 * x0) * t) * decay
  } else if (zeta < 1) {
    const omegaD = omega0 * Math.sqrt(1 - zeta * zeta)
    const decay = Math.exp(-zeta * omega0 * t)
    const cosine = Math.cos(omegaD * t)
    const sine = Math.sin(omegaD * t)
    displacement = decay * (x0 * cosine + ((v0 + zeta * omega0 * x0) / omegaD) * sine)
  } else {
    const rate = omega0 * Math.sqrt(zeta * zeta - 1)
    const slow = -zeta * omega0 + rate
    const fast = -zeta * omega0 - rate
    const c2 = (v0 - slow * x0) / (fast - slow)
    const c1 = x0 - c2
    displacement = c1 * Math.exp(slow * t) + c2 * Math.exp(fast * t)
  }

  return to + displacement
}

/**
 * Refuses a spring whose own `from`/`to` would be discarded.
 *
 * A track and a sequence step each define their own range and drive the spring
 * over `0..1`, so the physics stays independent of the units. A `from` or `to`
 * on the spring itself therefore cannot be honoured — and **dropping it
 * silently would animate to a value the caller never asked for while looking
 * like it had been obeyed.**
 */
export function assertSpringHasNoRange(config: SpringConfig, owner: string): void {
  if (config.from !== undefined || config.to !== undefined) {
    throw new Error(`[canvas] ${owner} defines its own \`from\`/\`to\`, so the spring cannot carry them as well — remove them from the spring config`)
  }
}

/** How long a spring takes to arrive, and how close counts as arrived. */
export interface SpringDurationOptions {
  /** Fraction of the distance still to travel when it counts as at rest. */
  readonly restDelta?: number
}

const DEFAULT_REST_DELTA = 0.005
/** Ceiling on the search, so a barely damped spring cannot run forever. */
const MAX_SETTLE_SECONDS = 100
const SETTLE_STEP_SECONDS = 1 / 240
const SETTLE_WINDOW_CYCLES = 1
const SETTLE_WINDOW_SAMPLES = 2

/**
 * Seconds until the spring has settled, so a render can be sized by the motion
 * rather than guessed.
 *
 * **Found by walking the closed form rather than solving the envelope**, and
 * the difference matters: the envelope is only an upper bound, and an
 * underdamped spring can sit inside it while still swinging through the target.
 * The honest answer is when it stops moving, not when the bound gets small.
 *
 * The rest window is a **whole oscillation** where there is one. A single
 * sample near the target proves nothing — an underdamped spring passes through
 * it twice a cycle — but a full cycle does, because the envelope decays
 * monotonically, so a spring quiet for one cycle can never leave again.
 */
export function springDuration(config: SpringConfig = {}, options: SpringDurationOptions = {}): number {
  const { restDelta = DEFAULT_REST_DELTA } = options
  const { from = 0, to = 1, stiffness = DEFAULT_STIFFNESS, damping = DEFAULT_DAMPING, mass = DEFAULT_MASS } = config

  const distance = Math.abs(to - from) || 1
  const threshold = restDelta * distance

  const omega0 = Math.sqrt(stiffness / mass)
  const zeta = damping / (2 * Math.sqrt(stiffness * mass))
  const restWindow =
    zeta < 1 - CRITICAL_BAND ? ((2 * Math.PI) / (omega0 * Math.sqrt(1 - zeta * zeta))) * SETTLE_WINDOW_CYCLES : SETTLE_STEP_SECONDS * SETTLE_WINDOW_SAMPLES

  let settled = 0
  for (let t = 0; t <= MAX_SETTLE_SECONDS; t += SETTLE_STEP_SECONDS) {
    if (Math.abs(spring(t, config) - to) > threshold) {
      settled = t
    } else if (t - settled >= restWindow) {
      break
    }
  }

  return settled + SETTLE_STEP_SECONDS
}

/**
 * Blends two numbers.
 *
 * **Deliberately unclamped**: `outBack` and `outElastic` return values beyond
 * `0..1`, and clamping here would flatten exactly the overshoot those curves
 * exist to produce.
 */
export function lerp(from: number, to: number, t: number): number {
  return from + (to - from) * t
}

/** Rescales a value from one range to another. */
export function mapRange(
  value: number,
  [inMin, inMax]: readonly [number, number],
  [outMin, outMax]: readonly [number, number],
  options: { readonly clamp?: boolean } = {},
): number {
  const span = inMax - inMin
  // An empty input range has no position to report. The start of the output
  // range is the honest answer, and avoids a NaN that would surface later as an
  // invalid layout value rather than here.
  if (span === 0) return outMin

  const t = (value - inMin) / span
  const mapped = lerp(outMin, outMax, t)
  if (!options.clamp) return mapped

  const low = Math.min(outMin, outMax)
  const high = Math.max(outMin, outMax)
  return Math.min(high, Math.max(low, mapped))
}

/**
 * A value this module knows how to blend.
 *
 * **An `Rgba` rather than a colour string**, because parsing belongs at the
 * package's one string boundary rather than inside every function that touches
 * a colour — see {@link mixColor}. A caller with a string parses it once and
 * animates the result.
 */
export type Animatable = number | Rgba | readonly (number | Rgba)[]

/** Whether a value is a colour rather than a number. */
function isRgba(value: unknown): value is Rgba {
  return typeof value === 'object' && value !== null && 'r' in value && 'g' in value && 'b' in value && 'a' in value
}

/**
 * Blends two values of the same kind.
 *
 * Numbers, colours, and arrays of either. **A colour string is not accepted**
 * — see {@link Animatable} — so a value this cannot blend is a type error
 * rather than a silent mis-blend.
 */
export function mix<T extends Animatable>(from: T, to: T, t: number): T {
  if (typeof from === 'number' && typeof to === 'number') {
    return lerp(from, to, t) as T
  }

  if (isRgba(from) && isRgba(to)) {
    return mixColor(from, to, t) as T
  }

  if (Array.isArray(from) && Array.isArray(to)) {
    if (from.length !== to.length) {
      throw new Error(`[canvas] mix() needs both arrays to be the same length (got ${from.length} and ${to.length})`)
    }
    return from.map((value, i) => mix(value as Animatable, (to as readonly Animatable[])[i] as Animatable, t)) as unknown as T
  }

  throw new Error(`[canvas] mix() needs both ends to be the same type (got ${typeof from} and ${typeof to})`)
}

/**
 * Interpolates across a keyframe track.
 *
 * **Values hold outside the declared range rather than extrapolating**, which
 * is what a keyframe track means: the first and last frames are states, not the
 * start of a slope. That is an input clamp on the track and is unrelated to the
 * output clamp being dropped from colour.
 */
export function interpolate<T extends Animatable>(
  t: number,
  stops: readonly number[],
  values: readonly T[],
  options: { readonly ease?: EasingName | ((t: number) => number) } = {},
): T {
  if (stops.length !== values.length) {
    throw new Error(`[canvas] interpolate() needs the same number of stops and values (got ${stops.length} and ${values.length})`)
  }
  if (stops.length < 2) {
    throw new Error('[canvas] interpolate() needs at least two stops')
  }
  for (let i = 1; i < stops.length; i++) {
    if ((stops[i] as number) <= (stops[i - 1] as number)) {
      throw new Error(`[canvas] interpolate() needs stops in ascending order (${stops[i - 1]} then ${stops[i]})`)
    }
  }

  if (t <= (stops[0] as number)) return values[0] as T
  if (t >= (stops[stops.length - 1] as number)) return values[values.length - 1] as T

  const upper = stops.findIndex(stop => stop > t)
  const lower = upper - 1
  const span = (stops[upper] as number) - (stops[lower] as number)
  const local = (t - (stops[lower] as number)) / span

  return mix(values[lower] as T, values[upper] as T, resolveEasing(options.ease)(local))
}

/** Resolves a name or a function into an easing, defaulting to linear. */
export function resolveEasing(easing: EasingName | ((t: number) => number) | undefined): (t: number) => number {
  if (easing === undefined) return CURVES.linear
  if (typeof easing === 'function') return easing

  const found = CURVES[easing]
  if (!found) throw new Error(`[canvas] unknown easing ${JSON.stringify(easing)}`)
  return found
}

/** What a track needs off a page: the time it sits at. */
export interface Sampled<T> {
  /** Value at this page, for the item at `index` when the track staggers. */
  at(page: { readonly time: number }, index?: number): T
  /** Seconds until the first item finishes. */
  readonly duration: number
  /** Seconds until `count` staggered items have all finished. */
  totalDuration(count: number): number
}

/** A reusable animation: what to move between, when, and how. */
export interface TrackConfig<T extends Animatable> {
  readonly from: T
  readonly to: T
  /** Seconds the motion lasts. Required unless `spring` supplies one. */
  readonly duration?: number
  readonly delay?: number
  /** Extra delay per item index, for staggering a row of elements. */
  readonly stagger?: number
  readonly ease?: EasingName | ((t: number) => number)
  /** Spring physics instead of an easing. Supplies its own duration. */
  readonly spring?: SpringConfig
}

/** One value moving from `from` to `to`. */
export function track<T extends Animatable>(config: TrackConfig<T>): Sampled<T> {
  const { from, to, delay = 0, stagger = 0, ease, spring: springConfig } = config

  if (springConfig && ease !== undefined) {
    throw new Error('[canvas] a track takes `spring` or `ease`, not both — a spring carries its own curve')
  }
  if (springConfig) assertSpringHasNoRange(springConfig, 'a track')
  if (delay < 0) throw new Error(`[canvas] track delay cannot be negative (got ${delay})`)
  if (stagger < 0) throw new Error(`[canvas] track stagger cannot be negative (got ${stagger})`)

  // A spring settles rather than ending, so its duration comes from the physics
  // unless the caller overrides it.
  const duration = config.duration ?? (springConfig ? springDuration(springConfig) : undefined)
  if (duration === undefined) {
    throw new Error('[canvas] a track needs a `duration` in seconds, or a `spring` to derive one from')
  }
  if (duration < 0) throw new Error(`[canvas] track duration cannot be negative (got ${duration})`)

  const easing = resolveEasing(ease)

  return {
    at(page, index = 0): T {
      const elapsed = page.time - delay - stagger * index

      // Finished is checked first so a zero-duration track reads as
      // instantaneous rather than as never having started — both conditions
      // are true at once when `duration` is 0.
      if (elapsed >= duration) return to
      if (elapsed <= 0) return from

      if (springConfig) {
        // Solved over the spring's own 0..1 and mapped onto the endpoints, so
        // `from` and `to` stay the track's business and the physics stays
        // independent of the units.
        return mix(from, to, spring(elapsed, { ...springConfig, from: 0, to: 1 }))
      }
      return mix(from, to, easing(elapsed / duration))
    },
    duration: delay + duration,
    totalDuration: (count: number) => delay + duration + stagger * Math.max(0, count - 1),
  }
}

/** One leg of a sequence. The start is wherever the previous leg finished. */
export interface SequenceStep<T extends Animatable> {
  readonly to: T
  readonly duration?: number
  readonly ease?: EasingName | ((t: number) => number)
  readonly spring?: SpringConfig
  /** Seconds to rest at `to` before the next step begins. */
  readonly hold?: number
}

/** A multi-step animation on a single value. */
export interface SequenceConfig<T extends Animatable> {
  readonly from: T
  readonly steps: readonly SequenceStep<T>[]
  readonly delay?: number
  readonly stagger?: number
}

interface PlannedStep<T extends Animatable> {
  from: T
  to: T
  start: number
  duration: number
  ease: (t: number) => number
  // `| undefined` rather than optional: `exactOptionalPropertyTypes` is on, so
  // an absent key and a key holding `undefined` are different types, and this
  // is built by spreading a value that may be either.
  spring: SpringConfig | undefined
}

/** Steps run one after another on one value. */
export function sequence<T extends Animatable>(config: SequenceConfig<T>): Sampled<T> {
  const { from, steps, delay = 0, stagger = 0 } = config

  if (steps.length === 0) throw new Error('[canvas] a sequence needs at least one step')
  if (delay < 0) throw new Error(`[canvas] sequence delay cannot be negative (got ${delay})`)
  if (stagger < 0) throw new Error(`[canvas] sequence stagger cannot be negative (got ${stagger})`)

  const planned: PlannedStep<T>[] = []
  let cursor = delay
  let previous = from

  for (const [index, step] of steps.entries()) {
    if (step.spring && step.ease !== undefined) {
      throw new Error(`[canvas] sequence step ${index} takes \`spring\` or \`ease\`, not both — a spring carries its own curve`)
    }
    if (step.spring) assertSpringHasNoRange(step.spring, `sequence step ${index}`)

    const duration = step.duration ?? (step.spring ? springDuration(step.spring) : undefined)
    if (duration === undefined) {
      throw new Error(`[canvas] sequence step ${index} needs a \`duration\` in seconds, or a \`spring\` to derive one from`)
    }
    if (duration < 0) throw new Error(`[canvas] sequence step ${index} duration cannot be negative (got ${duration})`)

    const hold = step.hold ?? 0
    if (hold < 0) throw new Error(`[canvas] sequence step ${index} hold cannot be negative (got ${hold})`)

    planned.push({ from: previous, to: step.to, start: cursor, duration, ease: resolveEasing(step.ease), spring: step.spring })

    // The hold sits after the motion, so the next step begins once it is over.
    cursor += duration + hold
    previous = step.to
  }

  const last = planned[planned.length - 1] as PlannedStep<T>
  // The trailing hold is not part of the length: nothing moves during it, so
  // counting it would pad every render that sizes itself from `duration`.
  const end = last.start + last.duration
  const final = last.to

  return {
    at(page, index = 0): T {
      const elapsed = page.time - stagger * index
      if (elapsed <= delay) return from
      if (elapsed >= end) return final

      // A linear scan rather than a binary search: a sequence is a handful of
      // steps, and the scan keeps the boundary rules in one readable place.
      for (const step of planned) {
        if (elapsed < step.start) return step.from
        if (elapsed >= step.start + step.duration) continue

        const local = elapsed - step.start
        if (step.spring) {
          return mix(step.from, step.to, spring(local, { ...step.spring, from: 0, to: 1 }))
        }
        return mix(step.from, step.to, step.ease(step.duration === 0 ? 1 : local / step.duration))
      }
      return final
    },
    duration: end,
    totalDuration: (count: number) => end + stagger * Math.max(0, count - 1),
  }
}

/** Every member's value at once, keyed as the caller named them. */
export type GroupValue<M extends Record<string, Sampled<unknown>>> = {
  [K in keyof M]: M[K] extends Sampled<infer V> ? V : never
}

/**
 * Runs several tracks together and samples them as one.
 *
 * **Kept in full on this surface**, where the Rust one takes a homogeneous
 * list: a mapped type can carry a different value type per key and Rust's type
 * system cannot express the same thing without erasing it. That divergence is a
 * language capability rather than a policy choice, so the surface that can
 * carry it does.
 */
export function parallel<M extends Record<string, Sampled<unknown>>>(members: M): Sampled<GroupValue<M>> {
  const entries = Object.entries(members)
  if (entries.length === 0) throw new Error('[canvas] a parallel group needs at least one member')

  return {
    at: (page, index = 0) => Object.fromEntries(entries.map(([name, member]) => [name, member.at(page, index)])) as GroupValue<M>,
    // The group is over when its last member is. Taken once at construction: a
    // member's duration cannot change afterwards.
    duration: Math.max(...entries.map(([, member]) => member.duration)),
    totalDuration: (count: number) => Math.max(...entries.map(([, member]) => member.totalDuration(count))),
  }
}

/** A colour as four channels: `r`, `g`, `b` in 0–255 and `a` in 0–1. */
export interface Rgba {
  readonly r: number
  readonly g: number
  readonly b: number
  readonly a: number
}

const CHANNEL_MAX = 255
/** Digits kept for an out-of-gamut channel, enough that a float32 survives. */
const EXTENDED_PRECISION = 6

const clampChannel = (value: number): number => Math.min(CHANNEL_MAX, Math.max(0, Math.round(value)))

/** Whether every channel sits inside what sRGB — and so hex — can write. */
const inGamut = ({ r, g, b }: Rgba): boolean => [r, g, b].every(c => c >= 0 && c <= CHANNEL_MAX)

/**
 * Writes a colour back as a string the renderer accepts.
 *
 * Hex ordinarily, `rgba()` once alpha is involved. **A colour outside sRGB
 * becomes `color(srgb …)`**, which carries the extended values verbatim and
 * reads back exactly — hex has no room for a channel above 255 or below 0, and
 * clamping instead would substitute a duller colour without saying so.
 */
export function formatColor(color: Rgba): string {
  const alpha = Math.min(1, Math.max(0, color.a))

  if (!inGamut(color)) {
    const [red, green, blue] = [color.r, color.g, color.b].map(c => Number((c / CHANNEL_MAX).toFixed(EXTENDED_PRECISION)))
    const tail = alpha >= 1 ? '' : ` / ${Number(alpha.toFixed(EXTENDED_PRECISION))}`
    return `color(srgb ${red} ${green} ${blue}${tail})`
  }

  const [red, green, blue] = [color.r, color.g, color.b].map(clampChannel)

  if (alpha >= 1) {
    return `#${[red, green, blue].map(c => (c as number).toString(16).padStart(2, '0')).join('')}`
  }
  // Trimmed so a half-way alpha reads as 0.5 rather than 0.5000000000000001.
  return `rgba(${red}, ${green}, ${blue}, ${Number(alpha.toFixed(3))})`
}

/**
 * Blends two colours in sRGB with a straight alpha, which is what the
 * compositing model expects.
 *
 * # Why this is not v1's signature
 *
 * v1 takes two **strings** and parses them here, because a browser handed it a
 * parser for free. **This package has no colour parser and deliberately so**:
 * one parser serves both surfaces and it lives in `meo-canvas-core`, so the
 * string boundary belongs at a `parseColor` rather than inside every function
 * that touches a colour. A limitation of v1's environment produced its
 * signature; a decision of ours produces this one.
 *
 * # Why `t` is not clamped
 *
 * v1 clamps it. **We drop that**, because CSS interpolates colour through an
 * overshooting curve and clamps where the colour becomes paint — so an
 * `outBack` driving a colour should be allowed to overshoot here and be
 * resolved later, exactly as it is for a number. `formatColor` is where an
 * out-of-gamut result stops being silent.
 */
export function mixColor(from: Rgba, to: Rgba, t: number): Rgba {
  return {
    r: from.r + (to.r - from.r) * t,
    g: from.g + (to.g - from.g) * t,
    b: from.b + (to.b - from.b) * t,
    a: from.a + (to.a - from.a) * t,
  }
}
