//! The animation helpers against v1's own numbers.
//!
//! # Why the comparison is exact
//!
//! Every value in `tests/assets/animate` was printed at JavaScript's default
//! precision, which is the shortest string that round-trips an `f64`. So both
//! surfaces parse the identical number, so the comparison is exact: a
//! difference of one bit is a difference. That is only affordable because the
//! module refuses fused multiply-add, which rounds once where JavaScript
//! rounds twice -- see `animate::easing`.
//!
//! **One table is not exact, and the sentence above must not be quoted without
//! it.** `spring.tsv` is compared within [`EXP_ULP`], because the closed form
//! evaluates `exp` and the two runtimes' `exp` differ in the last place. That
//! bound is measured rather than chosen, and it is one unit in the last place
//! -- not a tolerance anyone picked to make a row pass. Every other table here
//! is bit-exact.
//!
//! If a row outside that one ever needs an epsilon, the epsilon is the
//! finding.
//!
//! # What this table does not cover
//!
//! **Six hundred rows are a count, not a measure of how many things were
//! asked.** These four files exercise `easing` and `spring` and reach
//! `color`, `interpolate`, `track` and `sequence` **not at all** -- the
//! vectors are values of curves, and everything around the curves is
//! machinery no curve value can see. Those four are covered by unit tests
//! beside their own code. A reader who takes 612 rows as thoroughness will be
//! wrong about two thirds of the module.
//!
//! # Why v1 and not a derivation
//!
//! Generated by running v1's built module at tag `v9.0.2`, commit `890eed2`.
//! Deriving the table by hand would have made one reader's arithmetic the
//! referee for two implementations, which is the defect it exists to prevent,
//! one level up.

#![expect(
    clippy::float_cmp,
    reason = "the exact comparison IS the assertion. Both sides parse the \
              same shortest-round-trip decimal, so equality is the strongest \
              claim available and an epsilon here would hide the disagreement \
              this file exists to find. Where an epsilon is unavoidable it is \
              `EXP_ULP`, which is measured rather than chosen."
)]

use meo_canvas_core::{
    animate::{
        color::{Rgba, mix},
        easing::{Easing, cubic_bezier, steps},
        interpolate::{Animatable, keyframes, map_range},
        spring::Spring,
    },
    color::parse_channels,
};

/// The rows of one vector file, comments dropped and fields split.
///
/// **The count is checked against the one the file declares**, and that is not
/// ceremony. A hex colour begins with `#`, this format's comment character, so
/// a bare `#808080` in the first field is dropped by the filter below without
/// a word -- leaving a table that looks complete and tests fewer rows than it
/// lists. `parse-color.tsv` lost three rows exactly that way before its count
/// was compared with its generator's. Quoting fixed that file; the census is
/// what catches the next one, whatever swallows the row. The JavaScript walker
/// makes the same check, so a table cannot lose rows silently on either
/// surface.
fn rows(text: &'static str) -> Vec<Vec<&'static str>> {
    let data: Vec<Vec<&str>> = text
        .lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map(|line| line.split('\t').collect())
        .collect();
    let declared = text
        .lines()
        .find_map(|line| line.strip_prefix("# rows: "))
        .unwrap_or_else(|| {
            unreachable!("the table declares no `# rows:` count")
        })
        .trim()
        .parse::<usize>()
        .unwrap_or_else(|error| {
            unreachable!("unreadable `# rows:` count: {error}")
        });
    assert_eq!(
        data.len(),
        declared,
        "the table declares {declared} rows and {} survived parsing; a row is \
         being swallowed",
        data.len()
    );
    data
}

/// One field, unquoted where the table quoted it.
///
/// Quoting exists so a value beginning with `#` cannot be read as a comment.
fn field(value: &str) -> &str {
    value.trim_matches('"')
}

/// One field as the `f64` it round-trips to.
fn at(row: &[&str], index: usize) -> f64 {
    row[index]
        .parse()
        .unwrap_or_else(|error| unreachable!("{:?}: {error}", row[index]))
}

#[test]
fn every_curve_in_the_catalogue_matches_v1() {
    let table = include_str!("assets/animate/easing.tsv");
    let mut checked = 0;
    for row in rows(table) {
        let curve = Easing::ALL
            .into_iter()
            .find(|curve| curve.name() == row[0])
            .unwrap_or_else(|| {
                unreachable!("{} is not in the catalogue", row[0])
            });
        let (t, expected) = (at(&row, 1), at(&row, 2));
        let ours = curve.at(t);
        assert!(
            ours == expected,
            "{}({t}) is {ours} where v1 draws {expected}",
            row[0]
        );
        checked += 1;
    }
    // The catalogue and the table have to be the same size, or a curve we
    // never wrote would pass by not being asked about.
    assert_eq!(checked, 403, "the table changed size");
}

#[test]
fn the_catalogue_is_the_whole_catalogue() {
    let table = include_str!("assets/animate/easing.tsv");
    let named: std::collections::HashSet<&str> =
        rows(table).into_iter().map(|row| row[0]).collect();
    for curve in Easing::ALL {
        assert!(named.contains(curve.name()), "{} is untested", curve.name());
    }
    assert_eq!(
        named.len(),
        Easing::ALL.len(),
        "a curve is missing from one side"
    );
}

#[test]
fn a_bezier_solves_where_v1_solves() {
    let table = include_str!("assets/animate/bezier.tsv");
    for row in rows(table) {
        let (x1, y1) = (at(&row, 0), at(&row, 1));
        let (x2, y2) = (at(&row, 2), at(&row, 3));
        let (t, expected) = (at(&row, 4), at(&row, 5));
        let ours = cubic_bezier(x1, y1, x2, y2)(t);
        assert!(
            ours == expected,
            "cubic-bezier({x1}, {y1}, {x2}, {y2}) at {t} is {ours} where v1 \
             gives {expected}"
        );
    }
}

#[test]
fn steps_land_on_the_side_v1_lands_on() {
    let table = include_str!("assets/animate/steps.tsv");
    for row in rows(table) {
        let count = row[0]
            .parse::<u32>()
            .unwrap_or_else(|error| unreachable!("{error}"));
        let (t, expected) = (at(&row, 1), at(&row, 2));
        let ours =
            steps(count).unwrap_or_else(|error| unreachable!("{error}"))(t);
        assert!(
            ours == expected,
            "steps({count}) at {t} is {ours} where v1 gives {expected}"
        );
    }
}

#[test]
fn a_step_count_below_one_is_refused() {
    assert!(
        steps(0).is_err(),
        "steps(0) has no width to hold a value for"
    );
    assert!(steps(1).is_ok());
}

/// How many representable `f64` values lie between two numbers.
fn ulps_between(ours: f64, theirs: f64) -> i64 {
    #[expect(
        clippy::cast_possible_wrap,
        reason = "both values are small positive-exponent finites here, so \
                  the bit patterns are far from the sign boundary"
    )]
    let bits = |value: f64| value.to_bits() as i64;
    (bits(ours) - bits(theirs)).abs()
}

/// The only tolerance in this file, and it is measured rather than chosen.
///
/// **`Math.exp` differs between V8 and Rust's libm by one ulp on some
/// arguments**, which no amount of writing the same arithmetic can close: a
/// transcendental function is not required to be correctly rounded and the two
/// runtimes round differently. Verified by comparing the bit patterns of the
/// intermediates directly, at `stiffness 100, damping 10, t 0.35`:
///
/// ```text
/// omega_d  4021520cd1372fea   identical -- sqrt is exact by IEEE 754
/// cos      bfefce08c8431e64   identical
/// sin      3fbc3b3e5006087c   identical
/// exp      3fc63e397e022073 against V8's ...072   one ulp apart
/// ```
///
/// So the bound is one ulp, and it applies to the spring alone: **every other
/// function in this file compares exactly**, because none of them reaches
/// `exp`. Two rows of the 77 differ, both by exactly one.
///
/// **Measured over the rows in this table, and not proven for any other.**
/// V8 and libm may differ by more at other arguments; one ulp is what these
/// ones produced. **Anyone adding a spring row re-verifies the bound rather
/// than assuming it** -- otherwise the number reads as a property of `exp`
/// when it is a property of these samples, and it would stay correct through
/// every row that happened to agree and fail silently at the first that did
/// not.
const EXP_ULP: i64 = 1;

#[test]
fn a_spring_is_where_v1_puts_it() {
    let table = include_str!("assets/animate/spring.tsv");
    let mut regimes = (0, 0, 0);
    for row in rows(table) {
        let spring = Spring {
            from: at(&row, 0),
            to: at(&row, 1),
            stiffness: at(&row, 2),
            damping: at(&row, 3),
            mass: at(&row, 4),
            velocity: at(&row, 5),
        };
        let (t, expected) = (at(&row, 6), at(&row, 7));
        let ours = spring.at(t).unwrap_or_else(|error| unreachable!("{error}"));
        assert!(
            ulps_between(ours, expected) <= EXP_ULP,
            "a spring at {t}s is {ours} where v1 gives {expected}, which is \
             {} ulp apart (stiffness {}, damping {})",
            ulps_between(ours, expected),
            spring.stiffness,
            spring.damping
        );

        // Which regime each row exercised, so the table cannot quietly test
        // one solution three times.
        let zeta =
            spring.damping / (2.0 * (spring.stiffness * spring.mass).sqrt());
        if (zeta - 1.0).abs() < 1e-4 {
            regimes.1 += 1;
        } else if zeta < 1.0 {
            regimes.0 += 1;
        } else {
            regimes.2 += 1;
        }
    }
    // All three solutions are exercised, which a row count cannot tell you: a
    // table can hit one regime seventy-seven times and report coverage.
    // `stiffness 100, damping 20` gives a damping ratio of exactly 1 and is
    // what reaches the critical branch -- it was in the table before anyone
    // noticed it was the critical case, which is the argument for asserting
    // the regimes rather than assuming them.
    let (under, critical, over) = regimes;
    assert!(
        under > 0,
        "no underdamped row: the oscillating solution is untested"
    );
    assert!(
        critical > 0,
        "no critical row: the limiting solution is untested"
    );
    assert!(
        over > 0,
        "no overdamped row: the two-exponential solution is untested"
    );
}

#[test]
fn a_spring_without_an_equation_is_refused() {
    let none = Spring {
        stiffness: 0.0,
        ..Spring::default()
    };
    assert!(
        none.at(0.5).is_err(),
        "a spring with no stiffness has no equation"
    );
    assert!(
        Spring {
            damping: -1.0,
            ..Spring::default()
        }
        .at(0.5)
        .is_err()
    );
    assert!(
        Spring {
            mass: 0.0,
            ..Spring::default()
        }
        .at(0.5)
        .is_err()
    );
    assert!(Spring::default().at(0.5).is_ok());
}

/// One easing by the name the tables use, or `Linear` for the absent option.
///
/// `-` is the option omitted rather than `linear` named, and the two are
/// different calls on the JavaScript side even though they answer alike.
fn easing_named(name: &str) -> Easing {
    if name == "-" {
        return Easing::Linear;
    }
    Easing::ALL
        .into_iter()
        .find(|curve| curve.name() == name)
        .unwrap_or_else(|| unreachable!("{name} is not in the catalogue"))
}

#[test]
fn a_spring_settles_where_v1_settles_for_every_regime() {
    // `settles_after` had no direct test at all before this table: it was
    // reached only through `Track::duration` and `Sequence::plan`, so it could
    // have drifted with the suite staying green.
    let table = include_str!("assets/animate/spring-duration.tsv");
    let mut checked = 0;
    for row in rows(table) {
        let spring = Spring {
            from: at(&row, 0),
            to: at(&row, 1),
            stiffness: at(&row, 2),
            damping: at(&row, 3),
            mass: at(&row, 4),
            velocity: at(&row, 5),
        };
        let ours = spring
            .settles_after(at(&row, 6))
            .unwrap_or_else(|error| unreachable!("{error}"));
        let expected = at(&row, 7);
        assert!(
            ours == expected,
            "a spring {row:?} settles after {ours} where v1 says {expected}"
        );
        checked += 1;
    }
    assert_eq!(checked, 40);
}

#[test]
fn a_lerp_lands_where_v1_lands() {
    // `t` runs outside 0..1 here on purpose: the mix does not clamp, and a
    // table sampling only 0..1 could not tell an unclamped implementation from
    // a clamped one.
    let table = include_str!("assets/animate/lerp.tsv");
    for row in rows(table) {
        let (from, to, t) = (at(&row, 0), at(&row, 1), at(&row, 2));
        let ours = from.mix(to, t);
        let expected = at(&row, 3);
        assert!(
            ours == expected,
            "lerp({from}, {to}, {t}) is {ours} where v1 says {expected}"
        );
    }
}

#[test]
fn a_range_maps_where_v1_maps() {
    let table = include_str!("assets/animate/map-range.tsv");
    for row in rows(table) {
        let clamp = field(row[5]) == "true";
        let ours = map_range(
            at(&row, 0),
            (at(&row, 1), at(&row, 2)),
            (at(&row, 3), at(&row, 4)),
            clamp,
        );
        let expected = at(&row, 6);
        assert!(
            ours == expected,
            "map_range {row:?} is {ours} where v1 says {expected}"
        );
    }
}

#[test]
fn keyframes_land_where_v1_lands() {
    let table = include_str!("assets/animate/interpolate.tsv");
    for row in rows(table) {
        let t = at(&row, 0);
        let stops: Vec<f64> = field(row[1])
            .split(';')
            .map(|value| {
                value
                    .parse()
                    .unwrap_or_else(|error| unreachable!("{error}"))
            })
            .collect();
        let values: Vec<f64> = field(row[2])
            .split(';')
            .map(|value| {
                value
                    .parse()
                    .unwrap_or_else(|error| unreachable!("{error}"))
            })
            .collect();
        let ours = keyframes(t, &stops, &values, easing_named(field(row[3])))
            .unwrap_or_else(|error| unreachable!("{error}"));
        let expected = at(&row, 4);
        assert!(
            ours == expected,
            "keyframes {row:?} is {ours} where v1 says {expected}"
        );
    }
}

#[test]
fn a_mix_lands_where_v1_lands_for_the_kinds_rust_has() {
    // **`kind = array` is skipped, and the skip is the finding.** `Animatable`
    // is implemented for `f64` and `Rgba` and nothing else, so a JavaScript
    // caller can mix two arrays element-wise and a Rust caller cannot. The
    // table carries a `surface` column saying so rather than leaving the rows
    // out, because a gap absent from a table is a gap nobody compares.
    //
    // The colour rows are skipped here too, for a different reason: their
    // values are v1's CSS strings and this crate has no formatter to answer
    // with. `mix-color.tsv` walks the colour arithmetic where it can.
    let table = include_str!("assets/animate/mix.tsv");
    let (mut compared, mut skipped) = (0, 0);
    for row in rows(table) {
        if field(row[0]) != "number" || field(row[2]) != "value" {
            skipped += 1;
            continue;
        }
        let (from, to, t) = (at(&row, 3), at(&row, 4), at(&row, 5));
        let ours = from.mix(to, t);
        let expected = at(&row, 6);
        assert!(
            ours == expected,
            "mix({from}, {to}, {t}) is {ours} where v1 says {expected}"
        );
        compared += 1;
    }
    // A table read as all-skips would pass without asking anything.
    assert_eq!((compared, skipped), (5, 10));
}

/// A CSS colour as this crate reads it, or a panic naming the row.
fn parsed(css: &str) -> Rgba {
    let [r, g, b, a] = parse_channels(css)
        .unwrap_or_else(|| unreachable!("{css} did not parse"));
    Rgba { r, g, b, a }
}

#[test]
fn a_colour_parses_to_the_channels_the_author_wrote() {
    // **The one table here whose expected values are not v1's.** On alpha
    // neither reference was right: v1 quantises to eight bits and answers
    // `0.102` for `0.1`, and this crate answered `0.10000000149011612` while
    // the channels were `f32`. The browser answers `0.1` and is the tiebreak.
    //
    // The `note` column records what each surface gave before the rule
    // arrived, so a row that regresses says which of the two old answers it
    // regressed to rather than only that it moved.
    let table = include_str!("assets/animate/parse-color.tsv");
    let mut checked = 0;
    for row in rows(table) {
        let css = field(row[0]);
        let ours = parsed(css);
        let want = Rgba {
            r: at(&row, 2),
            g: at(&row, 3),
            b: at(&row, 4),
            a: at(&row, 5),
        };
        assert!(
            ours.r == want.r && ours.g == want.g && ours.b == want.b,
            "{css} parses to ({}, {}, {}) where the rule says ({}, {}, {})",
            ours.r,
            ours.g,
            ours.b,
            want.r,
            want.g,
            want.b
        );
        assert!(
            ours.a == want.a,
            "{css} parses to alpha {} where the author wrote {}",
            ours.a,
            want.a
        );
        checked += 1;
    }
    assert_eq!(checked, 18);
}

#[test]
fn a_colour_mixes_where_v1_mixes() {
    // **This is a weaker check than the JavaScript walker's, and the reason is
    // worth stating rather than hiding in a rounding call.** v1's `mixColor`
    // takes CSS strings and returns one; this crate takes and returns `Rgba`
    // and has no formatter, so the expected value has to be parsed back into
    // channels. Formatting is lossy: mixing `#000000` and `#ffffff` at `0.5`
    // gives exactly `127.5` here, and v1 writes `#808080`, which reads back as
    // `128`. The sub-byte half is real and the string cannot carry it.
    //
    // So this asserts the mix **to byte precision**, which is everything a hex
    // string holds, and the JavaScript side asserts the full string against
    // v1's own. A defect smaller than half a channel is invisible here and
    // visible there; neither walker alone covers `mixColor`, and the pair does.
    let table = include_str!("assets/animate/mix-color.tsv");
    let (mut compared, mut skipped) = (0, 0);
    for row in rows(table) {
        if field(row[3]) != "value" {
            skipped += 1;
            continue;
        }
        let ours =
            mix(parsed(field(row[0])), parsed(field(row[1])), at(&row, 2));
        let want = parsed(field(row[4]));
        let byte = |channel: f64| channel.round();
        assert!(
            byte(ours.r) == byte(want.r)
                && byte(ours.g) == byte(want.g)
                && byte(ours.b) == byte(want.b),
            "mixing {} and {} at {} gives ({}, {}, {}) where v1 draws {}",
            field(row[0]),
            field(row[1]),
            field(row[2]),
            ours.r,
            ours.g,
            ours.b,
            field(row[4])
        );
        // Alpha survives a string exactly where the channels do not: v1 writes
        // it as a decimal rather than a byte.
        assert!(
            ours.a == want.a,
            "mixing {} and {} at {} gives alpha {} where v1 draws {}",
            field(row[0]),
            field(row[1]),
            field(row[2]),
            ours.a,
            want.a
        );
        compared += 1;
    }
    // Mostly divergent by design; assert the agreeing rows were reached rather
    // than all skipped.
    assert_eq!((compared, skipped), (7, 8));
}
