//! The animation helpers against v1's own numbers.
//!
//! # Why the comparison is exact
//!
//! Every value in `tests/assets/animate` was printed at JavaScript's default
//! precision, which is the shortest string that round-trips an `f64`. So both
//! surfaces parse the identical number and **there is no tolerance here at
//! all**: a difference of one bit is a difference. That is only affordable
//! because the module refuses fused multiply-add, which rounds once where
//! JavaScript rounds twice -- see `animate::easing`.
//!
//! If a row ever needs an epsilon, the epsilon is the finding.
//!
//! # What this table does not cover
//!
//! **Six hundred rows are a count, not a measure of how many things were
//! asked.** These four files exercise `easing` and `spring` and reach
//! `color`, `interpolate`, `track` and `sequence` **not at all** -- the
//! vectors are values of curves, and everything around the curves is
//! machinery no curve value can see. Those four are covered by unit tests
//! beside their own code. A reader who takes 612 rows as thoroughness will be
//! wrong about two thirds of the module.
//!
//! # Why v1 and not a derivation
//!
//! Generated by running v1's built module at tag `v9.0.2`, commit `890eed2`.
//! Deriving the table by hand would have made one reader's arithmetic the
//! referee for two implementations, which is the defect it exists to prevent,
//! one level up.

#![expect(
    clippy::float_cmp,
    reason = "the exact comparison IS the assertion. Both sides parse the \
              same shortest-round-trip decimal, so equality is the strongest \
              claim available and an epsilon here would hide the disagreement \
              this file exists to find. Where an epsilon is unavoidable it is \
              `EXP_ULP`, which is measured rather than chosen."
)]

use meo_canvas_core::animate::{
    easing::{Easing, cubic_bezier, steps},
    spring::Spring,
};

/// The rows of one vector file, comments dropped and fields split.
fn rows(text: &'static str) -> impl Iterator<Item = Vec<&'static str>> {
    text.lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map(|line| line.split('\t').collect())
}

/// One field as the `f64` it round-trips to.
fn at(row: &[&str], index: usize) -> f64 {
    row[index]
        .parse()
        .unwrap_or_else(|error| unreachable!("{:?}: {error}", row[index]))
}

#[test]
fn every_curve_in_the_catalogue_matches_v1() {
    let table = include_str!("assets/animate/easing.tsv");
    let mut checked = 0;
    for row in rows(table) {
        let curve = Easing::ALL
            .into_iter()
            .find(|curve| curve.name() == row[0])
            .unwrap_or_else(|| {
                unreachable!("{} is not in the catalogue", row[0])
            });
        let (t, expected) = (at(&row, 1), at(&row, 2));
        let ours = curve.at(t);
        assert!(
            ours == expected,
            "{}({t}) is {ours} where v1 draws {expected}",
            row[0]
        );
        checked += 1;
    }
    // The catalogue and the table have to be the same size, or a curve we
    // never wrote would pass by not being asked about.
    assert_eq!(checked, 403, "the table changed size");
}

#[test]
fn the_catalogue_is_the_whole_catalogue() {
    let table = include_str!("assets/animate/easing.tsv");
    let named: std::collections::HashSet<&str> =
        rows(table).map(|row| row[0]).collect();
    for curve in Easing::ALL {
        assert!(named.contains(curve.name()), "{} is untested", curve.name());
    }
    assert_eq!(
        named.len(),
        Easing::ALL.len(),
        "a curve is missing from one side"
    );
}

#[test]
fn a_bezier_solves_where_v1_solves() {
    let table = include_str!("assets/animate/bezier.tsv");
    for row in rows(table) {
        let (x1, y1) = (at(&row, 0), at(&row, 1));
        let (x2, y2) = (at(&row, 2), at(&row, 3));
        let (t, expected) = (at(&row, 4), at(&row, 5));
        let ours = cubic_bezier(x1, y1, x2, y2)(t);
        assert!(
            ours == expected,
            "cubic-bezier({x1}, {y1}, {x2}, {y2}) at {t} is {ours} where v1 \
             gives {expected}"
        );
    }
}

#[test]
fn steps_land_on_the_side_v1_lands_on() {
    let table = include_str!("assets/animate/steps.tsv");
    for row in rows(table) {
        let count = row[0]
            .parse::<u32>()
            .unwrap_or_else(|error| unreachable!("{error}"));
        let (t, expected) = (at(&row, 1), at(&row, 2));
        let ours =
            steps(count).unwrap_or_else(|error| unreachable!("{error}"))(t);
        assert!(
            ours == expected,
            "steps({count}) at {t} is {ours} where v1 gives {expected}"
        );
    }
}

#[test]
fn a_step_count_below_one_is_refused() {
    assert!(
        steps(0).is_err(),
        "steps(0) has no width to hold a value for"
    );
    assert!(steps(1).is_ok());
}

/// How many representable `f64` values lie between two numbers.
fn ulps_between(ours: f64, theirs: f64) -> i64 {
    #[expect(
        clippy::cast_possible_wrap,
        reason = "both values are small positive-exponent finites here, so \
                  the bit patterns are far from the sign boundary"
    )]
    let bits = |value: f64| value.to_bits() as i64;
    (bits(ours) - bits(theirs)).abs()
}

/// The only tolerance in this file, and it is measured rather than chosen.
///
/// **`Math.exp` differs between V8 and Rust's libm by one ulp on some
/// arguments**, which no amount of writing the same arithmetic can close: a
/// transcendental function is not required to be correctly rounded and the two
/// runtimes round differently. Verified by comparing the bit patterns of the
/// intermediates directly, at `stiffness 100, damping 10, t 0.35`:
///
/// ```text
/// omega_d  4021520cd1372fea   identical -- sqrt is exact by IEEE 754
/// cos      bfefce08c8431e64   identical
/// sin      3fbc3b3e5006087c   identical
/// exp      3fc63e397e022073 against V8's ...072   one ulp apart
/// ```
///
/// So the bound is one ulp, and it applies to the spring alone: **every other
/// function in this file compares exactly**, because none of them reaches
/// `exp`. Two rows of the 77 differ, both by exactly one.
///
/// **Measured over the rows in this table, and not proven for any other.**
/// V8 and libm may differ by more at other arguments; one ulp is what these
/// ones produced. **Anyone adding a spring row re-verifies the bound rather
/// than assuming it** -- otherwise the number reads as a property of `exp`
/// when it is a property of these samples, and it would stay correct through
/// every row that happened to agree and fail silently at the first that did
/// not.
const EXP_ULP: i64 = 1;

#[test]
fn a_spring_settles_where_v1_settles() {
    let table = include_str!("assets/animate/spring.tsv");
    let mut regimes = (0, 0, 0);
    for row in rows(table) {
        let spring = Spring {
            from: at(&row, 0),
            to: at(&row, 1),
            stiffness: at(&row, 2),
            damping: at(&row, 3),
            mass: at(&row, 4),
            velocity: at(&row, 5),
        };
        let (t, expected) = (at(&row, 6), at(&row, 7));
        let ours = spring.at(t).unwrap_or_else(|error| unreachable!("{error}"));
        assert!(
            ulps_between(ours, expected) <= EXP_ULP,
            "a spring at {t}s is {ours} where v1 gives {expected}, which is \
             {} ulp apart (stiffness {}, damping {})",
            ulps_between(ours, expected),
            spring.stiffness,
            spring.damping
        );

        // Which regime each row exercised, so the table cannot quietly test
        // one solution three times.
        let zeta =
            spring.damping / (2.0 * (spring.stiffness * spring.mass).sqrt());
        if (zeta - 1.0).abs() < 1e-4 {
            regimes.1 += 1;
        } else if zeta < 1.0 {
            regimes.0 += 1;
        } else {
            regimes.2 += 1;
        }
    }
    // All three solutions are exercised, which a row count cannot tell you: a
    // table can hit one regime seventy-seven times and report coverage.
    // `stiffness 100, damping 20` gives a damping ratio of exactly 1 and is
    // what reaches the critical branch -- it was in the table before anyone
    // noticed it was the critical case, which is the argument for asserting
    // the regimes rather than assuming them.
    let (under, critical, over) = regimes;
    assert!(
        under > 0,
        "no underdamped row: the oscillating solution is untested"
    );
    assert!(
        critical > 0,
        "no critical row: the limiting solution is untested"
    );
    assert!(
        over > 0,
        "no overdamped row: the two-exponential solution is untested"
    );
}

#[test]
fn a_spring_without_an_equation_is_refused() {
    let none = Spring {
        stiffness: 0.0,
        ..Spring::default()
    };
    assert!(
        none.at(0.5).is_err(),
        "a spring with no stiffness has no equation"
    );
    assert!(
        Spring {
            damping: -1.0,
            ..Spring::default()
        }
        .at(0.5)
        .is_err()
    );
    assert!(
        Spring {
            mass: 0.0,
            ..Spring::default()
        }
        .at(0.5)
        .is_err()
    );
    assert!(Spring::default().at(0.5).is_ok());
}
