//! The Rust chart geometry against the TypeScript surface's own numbers.
//!
//! # Why the TypeScript is the reference
//!
//! v1 is the API baseline and Chrome is the behavioural one -- **but Chrome
//! has no charts**, so there is no browser to adjudicate this geometry. The
//! TypeScript side derived it from v1 and verified it by rendering. **A second
//! derivation from v1 would be a third set of numbers with nothing able to say
//! which was right**, so the port answers to the first instead.
//!
//! `tests/assets/chart/geometry.tsv` is generated by running `chart.ts`, not
//! by reading it.
//!
//! # What this cannot check
//!
//! **That the numbers are the right numbers.** Both surfaces agreeing on a
//! wrong bar edge passes every row here. The render tests on the TypeScript
//! side are what guard that, and until they exist this file proves agreement
//! and not correctness -- which is worth saying, because a green run looks the
//! same either way.

use meo_canvas::chart::geometry::{
    BAR_GROUP_SPACING, Bar, GRID_DIVISIONS, bar_layout, grid_lines,
    series_color, slice_angles, slice_path,
};

/// The rows, generated from `chart.ts`.
const TABLE: &str = include_str!("assets/chart/geometry.tsv");

/// The rows of one kind, as `(args, expected)`.
fn rows(kind: &str) -> impl Iterator<Item = (&'static str, &'static str)> {
    TABLE
        .lines()
        .filter(move |line| line.starts_with(kind))
        .filter_map(|line| {
            let mut parts = line.split('\t');
            let _ = parts.next()?;
            Some((parts.next()?, parts.next()?))
        })
}

#[test]
fn the_constants_are_the_ones_the_other_surface_uses() {
    for (name, value) in rows("constants") {
        let ours = match name {
            "GRID_DIVISIONS" => GRID_DIVISIONS.to_string(),
            "BAR_GROUP_SPACING" => BAR_GROUP_SPACING.to_string(),
            other => unreachable!("no constant named {other}"),
        };
        assert_eq!(ours, value, "{name} differs between the surfaces");
    }
}

#[test]
fn gridlines_fall_where_the_other_surface_puts_them() {
    let mut checked = 0;
    for (divisions, expected) in rows("gridLines") {
        let divisions: u32 = divisions
            .parse()
            .unwrap_or_else(|error| unreachable!("{error}"));
        let ours = grid_lines(divisions)
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(" ");
        assert_eq!(ours, expected, "gridLines({divisions})");
        checked += 1;
    }
    assert!(checked >= 4, "only {checked} gridline rows");
}

#[test]
fn a_series_takes_the_colour_the_other_surface_gives_it() {
    for (args, expected) in rows("seriesColor") {
        let ours = match args.split_once(" given=") {
            Some((index, given)) => {
                series_color(index.parse().unwrap_or(0), Some(given))
            }
            None => series_color(args.parse().unwrap_or(0), None),
        };
        assert_eq!(ours, expected, "seriesColor({args})");
    }
}

#[test]
fn bars_land_where_the_other_surface_lays_them() {
    let mut checked = 0;
    for (args, expected) in rows("barLayout") {
        // `labels series [[..],[..]] max`
        let open = args.find('[').unwrap_or(0);
        let close = args.rfind(']').unwrap_or(0);
        let head: Vec<&str> = args[..open].split_whitespace().collect();
        let (labels, series): (usize, usize) =
            (head[0].parse().unwrap_or(0), head[1].parse().unwrap_or(0));
        let values: Vec<Vec<f64>> = args[open + 1..close]
            .split("],[")
            .map(|row| {
                row.trim_matches(|c| c == '[' || c == ']')
                    .split(',')
                    .filter(|piece| !piece.is_empty())
                    .map(|piece| piece.parse().unwrap_or(0.0))
                    .collect()
            })
            .collect();
        let max: f64 = args[close + 1..].trim().parse().unwrap_or(0.0);

        let ours = bar_layout(labels, series, &values, max)
            .unwrap_or_else(|error| unreachable!("{error}"))
            .into_iter()
            .flatten()
            .map(|bar: Bar| {
                format!("{:.6},{:.6},{:.6}", bar.x, bar.width, bar.height)
            })
            .collect::<Vec<_>>()
            .join(" ");
        assert_eq!(ours, expected, "barLayout({args})");
        checked += 1;
    }
    assert!(checked >= 4, "only {checked} bar rows");
}

#[test]
fn slices_sweep_where_the_other_surface_sweeps_them() {
    for (values, expected) in rows("sliceAngles") {
        let values = parse_values(values);
        let ours = slice_angles(&values)
            .into_iter()
            .map(|(start, end)| format!("{start:.9},{end:.9}"))
            .collect::<Vec<_>>()
            .join(" ");
        assert_eq!(ours, expected, "sliceAngles({values:?})");
    }
}

#[test]
fn a_slice_is_the_same_path_string_on_both_surfaces() {
    // **The string rather than the numbers**: four decimals is what makes two
    // independently-computed paths comparable, and a path built by a
    // different route diverges in bytes with no numeric difference behind it.
    let mut checked = 0;
    for (args, expected) in rows("slicePath") {
        let (values, rest) = args.rsplit_once(' ').unwrap_or((args, "0"));
        let (values, index) = values.rsplit_once(' ').unwrap_or((values, "0"));
        let values = parse_values(values);
        let index: usize = index.parse().unwrap_or(0);
        let inner: f64 = rest.parse().unwrap_or(0.0);
        let (start, end) = slice_angles(&values)[index];
        assert_eq!(
            slice_path(start, end, 45.0, inner),
            expected,
            "slicePath({args})"
        );
        checked += 1;
    }
    assert!(checked >= 10, "only {checked} path rows");
}

#[test]
fn a_negative_value_is_refused_rather_than_drawn() {
    // v1 mis-draws these three ways; the port refuses. A stated divergence,
    // and the one row the generated table cannot carry because the other
    // surface throws for it too.
    assert!(bar_layout(1, 1, &[vec![-1.0]], 1.0).is_err());
    assert!(bar_layout(2, 1, &[vec![1.0, -0.5]], 1.0).is_err());
    assert!(bar_layout(1, 1, &[vec![0.0]], 0.0).is_ok());
}

/// `[1,2,3]` as numbers.
fn parse_values(text: &str) -> Vec<f64> {
    text.trim_matches(|c| c == '[' || c == ']')
        .split(',')
        .filter(|piece| !piece.is_empty())
        .map(|piece| piece.trim().parse().unwrap_or(0.0))
        .collect()
}
