//! Emits `packages/meo-canvas/src/generated/media-types.ts`: each encode
//! format's tag and `data:` media type, read from the renderer's table at
//! runtime, hence a test. The tag is the extension except `raw`, whose
//! extension is `bin`.

use std::{fmt::Write as _, fs, io, path::PathBuf};

use meo_canvas::Format;

/// Where the generated file lives when nothing else is named.
const CHECKED_IN: &str = "packages/meo-canvas/src/generated/media-types.ts";

/// The environment variable naming a different destination.
const DESTINATION: &str = "MEO_MEDIA_TYPES";

/// The tag a format crosses the addon boundary as.
const fn tag(format: Format) -> &'static str {
    match format {
        Format::Raw => "raw",
        other => other.extension(),
    }
}

#[test]
#[ignore = "writes a checked-in file; run through `just media-types`"]
fn emit_media_types() -> Result<(), io::Error> {
    let mut out = String::new();
    out.push_str(concat!(
        "// Generated by `just media-types` from `meo_canvas::Format`, which\n",
        "// delegates to the renderer's own table. Do not edit: `just ci`\n",
        "// regenerates this file and fails on a difference, so an edit here is a\n",
        "// build failure rather than a change.\n",
        "//\n",
        "// Both spellings of `ico` are accepted by browsers, so a hand-written\n",
        "// copy of this table can disagree with the renderer's without any test\n",
        "// failing. Generating it is what makes that disagreement impossible.\n",
        "\n",
        "/** The containers a canvas encodes to. */\n",
        "export type Format =\n",
    ));
    for (index, format) in Format::ALL.iter().enumerate() {
        let separator = if index == 0 { ' ' } else { '|' };
        let _ = writeln!(out, "  {separator} '{}'", tag(*format));
    }

    out.push_str(concat!(
        "\n",
        "/** The media type each format is served as in a `data:` URL. */\n",
        "export const MEDIA_TYPES: Readonly<Record<Format, string>> = {\n",
    ));
    for format in Format::ALL {
        let _ = writeln!(out, "  {}: '{}',", tag(*format), format.media_type());
    }
    out.push_str("}\n");

    let destination = std::env::var(DESTINATION).map_or_else(
        |_| PathBuf::from("../..").join(CHECKED_IN),
        PathBuf::from,
    );
    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&destination, out)?;
    eprintln!("media types: {} formats", Format::ALL.len());
    Ok(())
}
