//! Emits `packages/meo-canvas/src/generated/media-types.ts`.
//!
//! The formats a canvas encodes to, and the media type each is served as in a
//! `data:` URL. The TypeScript surface needs both — twelve tags in a union and
//! twelve entries in a record — and a transcribed copy can disagree with the
//! renderer silently: browsers accept both `image/x-icon` and the renderer's
//! `image/vnd.microsoft.icon` for `ico`, so a wrong entry there renders and
//! serves exactly like a right one.
//!
//! So the list is emitted from the Rust that already delegates to the renderer,
//! rather than transcribed. It is a test rather than a build script because the
//! values come from upstream's trait table at runtime and cannot be read out of
//! source text the way the arena tables and the wire enums can — the same
//! reason `arena-cases` is a test.
//!
//! Run by `just media-types`; `just media-types-check` regenerates to a
//! disposable path and diffs.
//!
//! # The tag is not the extension
//!
//! A format crosses the addon boundary as a **tag**, which is its extension
//! except for `Raw`: `ImageFormat::extension` answers `bin` there, because a
//! file of pixel bytes conventionally carries that name, while the tag a caller
//! writes is `raw`. That is the same rule `format_from_tag` applies in
//! `meo-canvas-node`, and it is stated once here rather than inferred twice.

use std::{fmt::Write as _, fs, io, path::PathBuf};

use meo_canvas::Format;

/// Where the generated file lives when nothing else is named.
const CHECKED_IN: &str = "packages/meo-canvas/src/generated/media-types.ts";

/// The environment variable naming a different destination.
const DESTINATION: &str = "MEO_MEDIA_TYPES";

/// The tag a format crosses the addon boundary as.
const fn tag(format: Format) -> &'static str {
    match format {
        Format::Raw => "raw",
        other => other.extension(),
    }
}

#[test]
#[ignore = "writes a checked-in file; run through `just media-types`"]
fn emit_media_types() -> Result<(), io::Error> {
    let mut out = String::new();
    out.push_str(concat!(
        "// Generated by `just media-types` from `meo_canvas::Format`, which\n",
        "// delegates to the renderer's own table. Do not edit: `just ci`\n",
        "// regenerates this file and fails on a difference, so an edit here is a\n",
        "// build failure rather than a change.\n",
        "//\n",
        "// Both spellings of `ico` are accepted by browsers, so a hand-written\n",
        "// copy of this table can disagree with the renderer's without any test\n",
        "// failing. Generating it is what makes that disagreement impossible.\n",
        "\n",
        "/** The containers a canvas encodes to. */\n",
        "export type Format =\n",
    ));
    for (index, format) in Format::ALL.iter().enumerate() {
        let separator = if index == 0 { ' ' } else { '|' };
        let _ = writeln!(out, "  {separator} '{}'", tag(*format));
    }

    out.push_str(concat!(
        "\n",
        "/** The media type each format is served as in a `data:` URL. */\n",
        "export const MEDIA_TYPES: Readonly<Record<Format, string>> = {\n",
    ));
    for format in Format::ALL {
        let _ = writeln!(out, "  {}: '{}',", tag(*format), format.media_type());
    }
    out.push_str("}\n");

    let destination = std::env::var(DESTINATION).map_or_else(
        |_| PathBuf::from("../..").join(CHECKED_IN),
        PathBuf::from,
    );
    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&destination, out)?;
    eprintln!("media types: {} formats", Format::ALL.len());
    Ok(())
}
