// Writes the landing page for the published reference, from the versions
// that are actually there.
//
// Generated rather than committed, and generated by reading the directory
// rather than a list: a hand-kept list of versions is wrong the first time a
// release is added and nothing reports it, where this cannot describe a
// version that is not published or omit one that is.
//
// # Prereleases
//
// This package publishes prereleases -- `v10.0.0-alpha.4` goes to npm's `next`
// dist-tag, never `latest`. The site follows the same rule: every version gets
// its own directory, and `latest/` is a copy of the newest version **without a
// prerelease part**. While no such version exists, `latest/` follows the newest
// prerelease and the page says so, because a reference for something is
// better than a reference for nothing -- but the moment a stable version is
// published it takes over, exactly as `npm install meo-canvas` would.
//
// Usage: node site-index.mjs <site-dir>

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const site = process.argv[2]
if (!site || !existsSync(site)) {
  process.stderr.write('Usage: node site-index.mjs <site-dir>\n')
  process.exit(1)
}

/** `v10.0.0-alpha.4` -> its comparable parts. A stable version outranks any prerelease of the same triple, as semver says. */
function parse(name) {
  const m = /^v(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?$/.exec(name)
  if (!m) return null
  return { major: +m[1], minor: +m[2], patch: +m[3], pre: m[4] ?? null }
}

/** Newest first. */
function newer(a, b) {
  const x = parse(a)
  const y = parse(b)
  if (x.major !== y.major) return y.major - x.major
  if (x.minor !== y.minor) return y.minor - x.minor
  if (x.patch !== y.patch) return y.patch - x.patch
  if (x.pre === null && y.pre !== null) return -1
  if (x.pre !== null && y.pre === null) return 1
  return String(y.pre).localeCompare(String(x.pre), undefined, { numeric: true })
}

const versions = readdirSync(site, { withFileTypes: true })
  .filter(entry => entry.isDirectory() && parse(entry.name) !== null)
  .map(entry => entry.name)
  .sort(newer)

if (versions.length === 0) {
  process.stderr.write('No versions in the site directory; nothing to index.\n')
  process.exit(1)
}

// `latest` is a copy of a version rather than a symlink, because the Pages
// artifact is a tarball and a symlink in it resolves to nothing. Which version
// it copies is recorded beside it so this page can say so.
const stampFile = join(site, 'latest', 'VERSION')
const latest = existsSync(stampFile) ? readFileSync(stampFile, 'utf8').trim() : versions[0]
const latestIsPrerelease = parse(latest)?.pre !== null

const older = versions
  .filter(version => version !== latest)
  .map(version => `        <li><a href="${version}/">${version}</a>${parse(version).pre !== null ? ' <small>prerelease</small>' : ''}</li>`)
  .join('\n')

writeFileSync(
  join(site, 'index.html'),
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>meo-canvas — JavaScript reference</title>
    <style>
      :root { color-scheme: light dark; }
      body {
        margin: 0 auto; padding: 3rem 1.5rem; max-width: 42rem;
        font: 16px/1.6 ui-sans-serif, system-ui, -apple-system, sans-serif;
      }
      h1 { margin-bottom: 0.25rem; font-size: 1.6rem; }
      p.lede { margin-top: 0; opacity: 0.75; }
      .latest {
        display: block; margin: 1.5rem 0; padding: 1rem 1.25rem;
        border: 1px solid color-mix(in srgb, currentColor 25%, transparent);
        border-radius: 8px; text-decoration: none; font-weight: 600;
      }
      .latest span { display: block; font-weight: 400; opacity: 0.7; font-size: 0.9rem; }
      h2 { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.06em; opacity: 0.6; }
      ul { list-style: none; padding: 0; columns: 3; }
      li { padding: 0.15rem 0; }
      small { opacity: 0.6; }
      a { color: inherit; }
      footer { margin-top: 2.5rem; font-size: 0.9rem; opacity: 0.7; }
      footer a { margin-right: 1rem; }
    </style>
  </head>
  <body>
    <h1>meo-canvas</h1>
    <p class="lede">
      The JavaScript API reference, generated from the type declarations each
      release ships. One page per published version.
    </p>

    <a class="latest" href="latest/">
      Latest — ${latest}
      <span>${
        latestIsPrerelease
          ? 'A prerelease: on npm this is <code>meo-canvas@next</code>, not <code>latest</code>. <code>latest/</code> here will move to the first stable release.'
          : 'Also at <code>latest/</code>, which follows the newest stable release — what <code>npm install meo-canvas</code> gives you.'
      }</span>
    </a>

${older ? `    <h2>Every version</h2>\n    <ul>\n${older}\n    </ul>` : ''}

    <footer>
      <a href="https://github.com/l7aromeo/meo-canvas">Source</a>
      <a href="https://docs.rs/meo-canvas">Rust reference</a>
      <a href="https://www.npmjs.com/package/meo-canvas">npm</a>
    </footer>
  </body>
</html>
`,
)

process.stdout.write(`Indexed ${versions.length} version(s); latest is ${latest}${latestIsPrerelease ? ' (prerelease)' : ''}.\n`)
